project_id = "rsjjvgyobtazxgeedmvi"

[functions.check-allowlist]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.send-question]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false
