import { GuideSection, CalloutBox, QuickTable, Checklist } from '../../GuideComponents';
import { GuideImagePlaceholder } from '../../GuideImagePlaceholder';

export function AgentReportsSection() {
  return (
    <div className="space-y-6">
      {/* A. Overview */}
      <GuideSection letter="A" color="bg-blue-600" title="Overview">
        <p className="text-sm text-muted-foreground mb-3">
          The Agent Reports hub is a <strong>centralized compliance incident tracker</strong> for behavioral and operational violations detected by the portal's automated monitoring systems. It provides Admin and HR users with tools to investigate, validate, escalate, or dismiss incidents.
        </p>
        <Checklist items={[
          'Incidents are auto-generated by EOD (End of Day) analytics edge functions — not manually created.',
          'Each report captures the agent, incident type, date, severity, frequency, and granular metadata.',
          'The hub defaults to the "Open" status filter so actionable items surface immediately.',
          'Every new incident triggers a Slack notification to #a_agent_reports and email alerts to leadership.',
        ]} />
        <GuideImagePlaceholder description="Agent Reports page showing summary cards, analytics panels, filters, and the incident reports table" />
      </GuideSection>

      {/* B. Incident Types */}
      <GuideSection letter="B" color="bg-red-600" title="Incident Types">
        <p className="text-sm text-muted-foreground mb-3">
          The system tracks <strong>9 distinct incident types</strong>, each with specific detection logic and metadata:
        </p>
        <QuickTable
          headers={['Incident', 'Trigger', 'Key Details Captured']}
          rows={[
            ['Late Login', 'Agent logs in >10 minutes after scheduled start', 'Scheduled start (mins), actual login (mins), minutes late'],
            ['Early Out', 'Agent logs out before scheduled shift end', 'Scheduled end (mins), actual logout (mins), minutes early'],
            ['No Logout', 'No logout event detected by end of day (11:59 PM EST)', 'Last login time, scheduled end, auto-logged-out flag'],
            ['Quota Not Met', 'Daily ticket count below assigned quota', 'Expected quota, actual total, shortfall, breakdown (email/chat/call)'],
            ['Time Not Met', 'Logged hours fall short of required shift hours', 'Required hours, logged hours, shortfall (mins), source'],
            ['High Ticket Gap', 'Average gap between tickets exceeds threshold (only when quota not met)', 'Avg gap (seconds), ticket count'],
            ['Excessive Restarts', 'Device restart duration exceeds 5-minute limit', 'Total restart duration (mins), limit, exceeded by'],
            ['Bio Overuse', 'Bio break time exceeds shift-based allowance (4 min for 8+ hrs, 2 min for shorter)', 'Bio time used, allowance, overage (seconds)'],
            ['Over Break', 'Total break time exceeds daily allowance plus 5-minute grace period', 'Break duration, allowance, overage'],
          ]}
        />
        <CalloutBox variant="info" title="Time Storage Format">
          Times stored in incident details as integers represent <strong>minutes from midnight</strong> (e.g., 720 = 12:00 PM). The UI automatically converts these to HH:MM format for display.
        </CalloutBox>
      </GuideSection>

      {/* C. Summary Cards */}
      <GuideSection letter="C" color="bg-purple-600" title="Summary Cards">
        <p className="text-sm text-muted-foreground mb-3">
          Four summary cards appear at the top of the page, providing a quick monthly overview:
        </p>
        <QuickTable
          headers={['Card', 'Shows']}
          rows={[
            ['Total Reports', 'All incidents for the selected month, regardless of status.'],
            ['Open', 'Incidents that have not been reviewed yet (default filtered view).'],
            ['Escalated', 'Incidents that have been escalated to outage requests for further action.'],
            ['Validated / Dismissed', 'Incidents confirmed as valid for coaching, or dismissed as false positives.'],
          ]}
        />
        <GuideImagePlaceholder description="Summary cards showing Total, Open, Escalated, and Validated/Dismissed counts for the selected month" />
      </GuideSection>

      {/* D. Filters */}
      <GuideSection letter="D" color="bg-teal-600" title="Filters">
        <p className="text-sm text-muted-foreground mb-3">
          The filter bar provides five selectors to narrow down the incident table:
        </p>
        <QuickTable
          headers={['Filter', 'Options', 'Default']}
          rows={[
            ['Year', 'Current year and 2 years prior', 'Current year'],
            ['Month', 'All 12 months', 'Current month'],
            ['Agent', 'Dropdown of all agents with at least one report', 'All Agents'],
            ['Incident Type', 'All 9 incident types', 'All Incidents'],
            ['Status', 'Open, Escalated, Validated, Dismissed', 'Open'],
          ]}
        />
        <CalloutBox variant="tip" title="Clear Filters">
          A "Clear" button appears when any filter is active. Clicking it resets agent, incident type, and status filters — but preserves the "Open" default for status to maintain actionable focus.
        </CalloutBox>
      </GuideSection>

      {/* E. Incident Table */}
      <GuideSection letter="E" color="bg-amber-600" title="Incident Reports Table">
        <p className="text-sm text-muted-foreground mb-3">
          The main table lists all incidents matching the active filters, sorted by <strong>incident date (newest first)</strong>:
        </p>
        <QuickTable
          headers={['Column', 'Content']}
          rows={[
            ['Agent', 'Name and email of the agent involved.'],
            ['Incident Type', 'Color-coded label (e.g., amber for Quota Not Met, red for No Logout).'],
            ['Date', 'Formatted incident date (e.g., "Feb 5, 2026").'],
            ['Severity', 'Badge — Low (green), Medium (amber), or High (red).'],
            ['Frequency', 'If >1 occurrence this week, shows "Nx this week" in amber. Otherwise a dash.'],
            ['Status', 'Badge — Open (blue), Escalated (purple), Validated (green), Dismissed (gray).'],
            ['Actions', 'Analytics icon (bar chart) to view agent analytics; eye icon to open report detail.'],
          ]}
        />
        <p className="text-sm text-muted-foreground mt-3">
          Clicking any row opens the <strong>Report Detail Dialog</strong> for investigation.
        </p>
        <GuideImagePlaceholder description="Incident reports table showing columns for Agent, Incident Type, Date, Severity, Frequency, Status, and Actions" />
      </GuideSection>

      {/* F. Report Detail Dialog */}
      <GuideSection letter="F" color="bg-indigo-600" title="Report Detail Dialog">
        <p className="text-sm text-muted-foreground mb-3">
          The detail dialog provides a full investigation view of a single incident:
        </p>
        <Checklist items={[
          'Header shows the incident type icon, label, agent name, date, severity badge, and status badge.',
          'Incident Details section displays type-specific metadata (e.g., scheduled vs. actual times, quotas, shortfalls).',
          'Frequency Alert appears when the agent has multiple incidents of the same type in the same week.',
          'Notes field allows admins to add investigation context before taking action.',
          'Review section shows who reviewed the report and when (if already actioned).',
        ]} />

        <h4 className="font-semibold text-sm mt-4 mb-2">Available Actions (Admin/HR Only)</h4>
        <QuickTable
          headers={['Action', 'Effect']}
          rows={[
            ['Validate', 'Marks the report as confirmed for coaching. Status changes to "Validated" (green).'],
            ['Dismiss', 'Marks the report as a false positive. Status changes to "Dismissed" (gray).'],
            ['Escalate to Outage', 'Creates a "for_review" outage request and marks the report as "Escalated" (purple). Only available for escalatable incident types.'],
          ]}
        />
        <GuideImagePlaceholder description="Report Detail Dialog showing incident metadata, notes field, and action buttons (Validate, Dismiss, Escalate)" />
      </GuideSection>

      {/* G. Escalation Workflow */}
      <GuideSection letter="G" color="bg-red-600" title="Escalation to Outage Requests">
        <p className="text-sm text-muted-foreground mb-3">
          Four incident types can be escalated directly into <strong>Outage Requests</strong> for formal tracking:
        </p>
        <QuickTable
          headers={['Incident Type', 'Creates Outage Reason', 'Time Calculation']}
          rows={[
            ['Late Login', 'Late Login', 'Start: scheduled start + 5 min grace → End: 1 min before actual login'],
            ['Early Out', 'Undertime', 'Start: actual logout → End: scheduled end'],
            ['Time Not Met', 'Undertime', 'Start: scheduled end - shortfall → End: scheduled end'],
            ['Excessive Restarts', 'Equipment Issue', 'Default 1-hour window starting at 9:00 AM (or restart duration)'],
          ]}
        />
        <CalloutBox variant="warning" title="Duplicate Prevention">
          The system checks for existing outage requests with the same agent, date, and reason before creating a new one. If a duplicate is detected, the escalation is blocked with a warning toast.
        </CalloutBox>
        <p className="text-sm text-muted-foreground mt-3">
          A <strong>confirmation dialog</strong> appears before escalation, showing the agent name, date, calculated time range, and outage reason. The outage request is created with a <code>for_review</code> status.
        </p>
      </GuideSection>

      {/* H. Analytics Panels */}
      <GuideSection letter="H" color="bg-emerald-600" title="Analytics Panels">
        <p className="text-sm text-muted-foreground mb-3">
          Three analytics panels are available on the Agent Reports page:
        </p>

        <h4 className="font-semibold text-sm mb-2">1. EOD (End of Day) Team Analytics</h4>
        <p className="text-sm text-muted-foreground mb-3">
          A collapsible panel showing <strong>daily team-wide performance</strong> metrics. Triggered automatically at 11:59 PM EST via a scheduled edge function. Includes:
        </p>
        <Checklist items={[
          'Attendance: Active vs scheduled agents, on-time rate, full-shift completion rate.',
          'Productivity: Total tickets (email/chat/call), quota achievement rate, average gap.',
          'Time: Average logged hours vs required hours.',
          'Compliance: Clean-sheet rate and incident type breakdown.',
          'Overall status indicator: Good (green), Warning (amber), Critical (red).',
        ]} />

        <h4 className="font-semibold text-sm mt-4 mb-2">2. EOW (End of Week) Team Analytics</h4>
        <p className="text-sm text-muted-foreground mb-3">
          A collapsible panel showing <strong>weekly aggregated performance</strong>. Generated every Monday at 12:00 AM EST. Covers the same categories as EOD but aggregated across the full Mon–Sun period. Includes trend indicators and weekly comparisons.
        </p>

        <h4 className="font-semibold text-sm mt-4 mb-2">3. Individual Agent Analytics</h4>
        <p className="text-sm text-muted-foreground mb-3">
          Accessible via the bar chart icon on any report row, or from the dedicated panel. Shows <strong>per-agent performance</strong> including:
        </p>
        <Checklist items={[
          'Incident breakdown by type (bar chart).',
          'Monthly trend analysis (increasing, decreasing, or stable).',
          'Daily/weekly performance views with a 7-day breakdown grid (Mon–Sun).',
          'Available to all roles — not restricted to Admin/HR.',
        ]} />
        <GuideImagePlaceholder description="EOD Analytics panel showing attendance, productivity, time, and compliance sections with status indicators" />
      </GuideSection>

      {/* I. Notifications */}
      <GuideSection letter="I" color="bg-orange-600" title="Notifications & Alerts">
        <QuickTable
          headers={['Channel', 'Trigger', 'Recipients']}
          rows={[
            ['Slack (#a_agent_reports)', 'New incident report generated', 'Channel members'],
            ['Slack (#a_agent_reports)', 'EOD/EOW analytics summary', 'Channel members'],
            ['Email', 'New incident report', 'Admin, HR, Super Admin (de-duplicated)'],
            ['Email', 'EOD/EOW analytics digest', 'Admin, HR, Super Admin (de-duplicated)'],
            ['Slack (real-time)', 'Bio overuse, excessive restarts, overbreak, late login, early out, no logout, time not met', 'Routed to #a_agent_reports with creative messaging'],
          ]}
        />
        <CalloutBox variant="info" title="Team-Wide Exclusions">
          EOD and EOW team analytics <strong>exclude</strong> agents in Team Lead, Technical Support, and Logistics positions to maintain core agent performance accuracy.
        </CalloutBox>
      </GuideSection>

      {/* J. Access Control */}
      <GuideSection letter="J" color="bg-gray-600" title="Access Control">
        <QuickTable
          headers={['Role', 'Can View Reports', 'Can Take Action', 'Can View Analytics']}
          rows={[
            ['User / Agent', 'No', 'No', 'Yes (individual only)'],
            ['Admin', 'Yes', 'Yes (validate, dismiss, escalate)', 'Yes (all panels)'],
            ['HR', 'Yes', 'Yes (validate, dismiss, escalate)', 'Yes (all panels)'],
            ['Super Admin', 'Yes', 'Yes (validate, dismiss, escalate)', 'Yes (all panels)'],
          ]}
        />
        <CalloutBox variant="tip" title="Report Generation">
          Incident reports are created exclusively by automated backend processes (EOD analytics edge functions). There is no manual report creation interface — this ensures consistency and eliminates human bias in incident detection.
        </CalloutBox>
      </GuideSection>
    </div>
  );
}
