import { GuideSection, CalloutBox, Checklist, QuickTable } from '../../GuideComponents';
import { GuideImagePlaceholder } from '../../GuideImagePlaceholder';

export function OutageRequestsSection() {
  return (
    <>
      {/* 1. Overview */}
      <GuideSection letter="A" color="bg-orange-500" title="Overview & Purpose">
        <p className="text-muted-foreground mb-4">
          Outage Requests (formerly Leave Requests) let agents formally report periods of unavailability — power outages, medical leave, late logins, and more. Each request flows through an approval pipeline, is tracked with a unique reference number, and feeds into Outage Statistics and the Reliability score on the Team Scorecard.
        </p>

        <h3 className="font-semibold mb-2">Key Concepts</h3>
        <Checklist items={[
          'Every request receives a unique reference number (e.g., LR-0001).',
          'All times are entered and displayed in Eastern Standard Time (EST).',
          'Duration (hours and days) is auto-calculated from the start/end date and time.',
          'Requests can be created manually by agents or auto-generated by the system.',
          'The Reliability metric deducts 1% per unplanned outage day (Planned Leave exempt).',
        ]} />

        <GuideImagePlaceholder description="Screenshot: Outage Request page overview showing the form and My Requests table" />
      </GuideSection>

      {/* 2. Request Form */}
      <GuideSection letter="B" color="bg-orange-400" title="Submitting a Request — Form Fields">
        <p className="text-muted-foreground mb-4">
          The request form adapts based on whether you are in the Agent Directory and whether you have Admin/HR privileges.
        </p>

        <h3 className="font-semibold mb-2">Form Fields</h3>
        <QuickTable
          headers={['Field', 'Required', 'Auto-Populated?', 'Notes']}
          rows={[
            ['Agent Name', 'Yes', 'Yes (directory users)', 'Admins see a dropdown of all agents; selecting one auto-fills Team Lead, Role, and Client.'],
            ['Client Name', 'Yes', 'Yes (if 1 client)', 'Limited to the agent\'s assigned clients from the directory.'],
            ['Team Lead Name', 'Yes', 'Yes (directory users)', 'Admins can override via dropdown.'],
            ['Role', 'Yes', 'Yes (directory users)', 'Admins can override via dropdown.'],
            ['Start Date', 'Yes', 'No', 'Date picker.'],
            ['End Date', 'Yes', 'No', 'Must be on or after start date.'],
            ['Start Time (EST)', 'Yes', 'Defaults to 09:00', '30-minute interval picker.'],
            ['End Time (EST)', 'Yes', 'Defaults to 17:00', '30-minute interval picker.'],
            ['Outage Reason', 'Yes', 'No', 'Dropdown (see list below).'],
            ['Attachments', 'No', 'No', 'Up to 3 files. Stored as JSON array for multi-file support.'],
            ['Remarks', 'No', 'No', 'Visible on auto-generated requests; editable by agent and admin.'],
          ]}
        />

        <GuideImagePlaceholder description="Screenshot: Request form with auto-populated fields highlighted" />

        <h3 className="font-semibold mb-2 mt-4">Outage Reasons</h3>
        <QuickTable
          headers={['Reason', 'Typical Use Case', 'Scorecard Impact']}
          rows={[
            ['Power Outage', 'Electricity issues preventing work.', 'Deducts from Reliability'],
            ['Wi-Fi Issue', 'Internet connectivity problems.', 'Deducts from Reliability'],
            ['Medical Leave', 'Health-related absence.', 'Deducts from Reliability'],
            ['Planned Leave', 'Pre-scheduled vacation or time off.', 'No deduction (exempt)'],
            ['Equipment Issue', 'Computer or hardware failure.', 'Deducts from Reliability'],
            ['Late Login', 'Agent logged in after scheduled start.', 'Deducts from Reliability'],
            ['Undertime', 'Left earlier than scheduled end.', 'Deducts from Reliability'],
            ['Unplanned', 'Emergency or unexpected absence.', 'Deducts from Reliability'],
          ]}
        />

        <h3 className="font-semibold mb-2 mt-4">Validation Rules</h3>
        <Checklist items={[
          'All required fields must be filled before submission.',
          'End date must be on or after the start date.',
          'Start time must be before end time (overnight shifts handled automatically).',
          'Agent must have at least one assigned client.',
          'Multi-file upload capped at 3 attachments per request.',
        ]} />

        <CalloutBox variant="info" title="Admin Auto-Fill">
          When an Admin selects an agent from the dropdown, the form automatically fills in Team Lead, Role, and Client (if the agent has only one). This prevents data entry mistakes and speeds up the process.
        </CalloutBox>
      </GuideSection>

      {/* 3. Conflict Detection & Override */}
      <GuideSection letter="C" color="bg-amber-500" title="Conflict Detection & Override Workflow">
        <p className="text-muted-foreground mb-4">
          Before a request is created, the system checks for scheduling conflicts — overlapping date and time ranges for the same client among non-canceled/declined requests.
        </p>

        <h3 className="font-semibold mb-2">How Conflict Detection Works</h3>
        <Checklist items={[
          'System queries existing approved/pending requests for the same client and role.',
          'Checks both date overlap AND time overlap (handles overnight shifts).',
          'If a conflict is found, a warning is shown with the conflicting agent names.',
          'The user can still submit by providing an override reason.',
          'Override requests are created with "Pending Override" status.',
        ]} />

        <GuideImagePlaceholder description="Screenshot: Conflict warning message with override reason input" />

        <h3 className="font-semibold mb-2 mt-4">Override Request Flow</h3>
        <QuickTable
          headers={['Step', 'Action', 'Who']}
          rows={[
            ['1', 'System detects overlapping approved/pending request and shows warning.', 'System'],
            ['2', 'Agent enters an override reason explaining the necessity.', 'Agent'],
            ['3', 'Request is submitted with "Pending Override" status.', 'Agent'],
            ['4', 'Email notification sent to Admin, HR, and Super Admin.', 'System'],
            ['5', 'Admin/HR reviews the override and approves or declines.', 'Admin/HR'],
          ]}
        />

        <CalloutBox variant="warning" title="Override Requests Need Justification">
          Always provide a clear, specific reason when submitting an override. Vague reasons may lead to the request being declined.
        </CalloutBox>
      </GuideSection>

      {/* 4. Request Statuses */}
      <GuideSection letter="D" color="bg-yellow-500" title="Request Status Lifecycle">
        <p className="text-muted-foreground mb-4">
          Every outage request moves through a defined status pipeline. The active tab defaults to "Pending" to surface actionable items first.
        </p>

        <h3 className="font-semibold mb-2">Status Definitions</h3>
        <QuickTable
          headers={['Status', 'Badge Color', 'Meaning', 'Next Steps']}
          rows={[
            ['Pending', 'Yellow', 'Awaiting admin/HR review.', 'Admin approves or declines.'],
            ['For Review', 'Blue', 'Auto-generated request needs admin attention.', 'Admin reviews and approves or declines.'],
            ['Pending Override', 'Orange', 'Conflict exists; override justification submitted.', 'Admin reviews override reason.'],
            ['Approved', 'Green', 'Request has been approved.', 'Outage confirmed; feeds Reliability score.'],
            ['Declined', 'Red', 'Request was rejected.', 'Agent can check remarks for reason.'],
            ['Canceled', 'Gray', 'Agent canceled their own request.', 'No further action needed.'],
          ]}
        />

        <GuideImagePlaceholder description="Screenshot: Tab bar showing Pending → For Review → Override → All Requests with badge counts" />

        <h3 className="font-semibold mb-2 mt-4">Tab Order (Prioritized)</h3>
        <Checklist items={[
          'Pending — standard requests awaiting approval (default active tab).',
          'For Review — auto-generated requests needing admin attention.',
          'Override Requests — conflict overrides needing special review (Admin/HR only).',
          'All Requests — complete list across all statuses.',
        ]} />

        <CalloutBox variant="tip" title="Cancellation Rules">
          Agents can cancel their own <strong>pending</strong> requests only. Once approved, only an Admin/HR can change the status. Declined or canceled requests cannot be re-activated.
        </CalloutBox>
      </GuideSection>

      {/* 5. Auto-Generated Requests */}
      <GuideSection letter="E" color="bg-blue-500" title="Auto-Generated Outage Requests">
        <p className="text-muted-foreground mb-4">
          The system automatically creates outage requests in specific scenarios to reduce manual data entry and ensure compliance tracking.
        </p>

        <h3 className="font-semibold mb-2">Late Login Auto-Requests</h3>
        <p className="text-sm text-muted-foreground mb-3">
          When an agent logs in more than 10 minutes after their scheduled start time, the system automatically creates a "Late Login" outage request.
        </p>

        <QuickTable
          headers={['Detail', 'Value']}
          rows={[
            ['Trigger', 'Agent logs in > 10 minutes after scheduled start.'],
            ['Status', '"For Review" (blue badge).'],
            ['Outage Reason', '"Late Login"'],
            ['Start Time', 'Scheduled start + 5-minute grace period.'],
            ['End Time', '1 minute before actual login time.'],
            ['Badge', '"Auto" indicator on the request row.'],
            ['Duplicate Prevention', 'Skipped if a Late Login request already exists for the same agent and date.'],
          ]}
        />

        <GuideImagePlaceholder description="Screenshot: Auto-generated request row with 'Auto' badge and 'For Review' status" />

        <h3 className="font-semibold mb-2 mt-4">Example: Late Login Calculation</h3>
        <div className="p-4 bg-muted/50 rounded-lg my-4 text-sm space-y-2">
          <p><strong>Scheduled Start:</strong> 9:00 AM EST</p>
          <p><strong>Actual Login:</strong> 9:25 AM EST (25 minutes late)</p>
          <p><strong>System Creates:</strong></p>
          <ul className="list-disc list-inside pl-4 space-y-1">
            <li>Reason: "Late Login"</li>
            <li>Start Time: 9:05 AM (schedule + 5 min grace)</li>
            <li>End Time: 9:24 AM (1 min before login)</li>
            <li>Duration: 19 minutes</li>
            <li>Status: "For Review"</li>
          </ul>
        </div>

        <h3 className="font-semibold mb-2 mt-4">Escalation-Generated Requests</h3>
        <p className="text-sm text-muted-foreground mb-3">
          Admins can escalate Agent Report incidents into outage requests directly from the Agent Reports page.
        </p>

        <QuickTable
          headers={['Incident Type', 'Resulting Outage Reason', 'Time Calculation']}
          rows={[
            ['LATE_LOGIN', 'Late Login', 'Start: scheduled start + 5 min grace → End: 1 min before actual login.'],
            ['EARLY_OUT', 'Undertime', 'Start: actual logout → End: scheduled end.'],
            ['TIME_NOT_MET', 'Undertime', 'Start: scheduled end − shortfall → End: scheduled end.'],
            ['EXCESSIVE_RESTARTS', 'Equipment Issue', 'Default time range provided by the system.'],
          ]}
        />

        <Checklist items={[
          'All escalation-generated requests use "For Review" status.',
          'The original Agent Report is marked as "Escalated" with a link to the outage.',
          'Duplicate prevention: system skips if same agent, date, and reason already exists.',
        ]} />

        <CalloutBox variant="info" title="Remarks Field on Auto Requests">
          Auto-generated requests include a Remarks field that both the agent and admin can edit. This allows agents to provide context (e.g., "Traffic delay") and admins to add notes before approving or declining.
        </CalloutBox>
      </GuideSection>

      {/* 6. My Requests Table */}
      <GuideSection letter="F" color="bg-orange-400" title="My Requests Table & Actions">
        <p className="text-muted-foreground mb-4">
          The request table lists all outage requests with filtering by status tab. Admins see all requests across the team; regular users see only their own.
        </p>

        <h3 className="font-semibold mb-2">Table Columns</h3>
        <QuickTable
          headers={['Column', 'Description']}
          rows={[
            ['Checkbox', 'Bulk selection for Admin/HR batch operations.'],
            ['Reference #', 'Unique identifier (e.g., LR-0001).'],
            ['Submitted', 'Date the request was created.'],
            ['Start Date', 'When the outage begins.'],
            ['End Date', 'When the outage ends.'],
            ['Client', 'The affected client account.'],
            ['Reason', 'Outage type (Power Outage, Late Login, etc.).'],
            ['Status', 'Current status badge with icon.'],
            ['Hours', 'Total outage hours (auto-calculated).'],
            ['Days', 'Total outage days (auto-calculated).'],
            ['Actions', 'Context-sensitive action buttons.'],
          ]}
        />

        <GuideImagePlaceholder description="Screenshot: My Requests table with status badges and action buttons" />

        <h3 className="font-semibold mb-2 mt-4">Action Buttons by Role</h3>
        <QuickTable
          headers={['Action', 'Icon', 'Who Can Use', 'Available When']}
          rows={[
            ['Edit', 'Pencil', 'Owner OR Admin', 'Status is Pending or For Review. Users can only edit Remarks; Admins edit all fields.'],
            ['Cancel', 'X', 'Owner only', 'Status is Pending.'],
            ['Approve', 'Checkmark', 'Admin/HR', 'Status is Pending, For Review, or Pending Override.'],
            ['Decline', 'X Circle', 'Admin/HR', 'Status is Pending, For Review, or Pending Override.'],
            ['History', 'Clock', 'Everyone', 'Always available — opens audit log.'],
            ['Delete', 'Trash', 'Admin/HR', 'Always available.'],
          ]}
        />

        <h3 className="font-semibold mb-2 mt-4">Edit Permissions (Role-Based)</h3>
        <QuickTable
          headers={['Role', 'Can Edit', 'Behavior on Save']}
          rows={[
            ['Regular User', 'Remarks field only', 'Core fields (dates, times, reason) are read-only.'],
            ['Admin / Super Admin / HR', 'All fields', 'Resets status to Pending; clears previous review.'],
          ]}
        />

        <h3 className="font-semibold mb-2 mt-4">Bulk Operations (Admin/HR)</h3>
        <Checklist items={[
          'Select multiple requests using checkboxes.',
          'Bulk delete available for Admin/HR users.',
          'Confirmation dialog required before bulk deletion.',
        ]} />

        <CalloutBox variant="warning" title="Admin Edit Resets Status">
          When an Admin edits any field on an existing request, the status automatically resets to "Pending" and the previous review decision is cleared. This ensures the updated request goes through approval again.
        </CalloutBox>
      </GuideSection>

      {/* 7. Audit Log */}
      <GuideSection letter="G" color="bg-amber-400" title="Audit Log & History Tracking">
        <p className="text-muted-foreground mb-4">
          Every change to an outage request is logged in the audit history, providing a complete paper trail of modifications.
        </p>

        <h3 className="font-semibold mb-2">Tracked Changes</h3>
        <Checklist items={[
          'Field-level diff: shows old value → new value for each changed field.',
          'Tracked fields: agent name, client, team lead, role, dates, times, reason, attachments, status, remarks.',
          'Each entry records who made the change and when.',
          'History is accessible via the Clock icon on any request row.',
        ]} />

        <GuideImagePlaceholder description="Screenshot: Audit log dialog showing change history with old → new values" />

        <CalloutBox variant="info" title="Non-Destructive History">
          The audit log is append-only. Entries cannot be edited or deleted, ensuring a reliable compliance trail for all outage requests.
        </CalloutBox>
      </GuideSection>

      {/* 8. Notifications */}
      <GuideSection letter="H" color="bg-orange-300" title="Notifications & Alerts">
        <p className="text-muted-foreground mb-4">
          The system sends email notifications at key points in the request lifecycle.
        </p>

        <h3 className="font-semibold mb-2">Notification Triggers</h3>
        <QuickTable
          headers={['Event', 'Recipients', 'Content']}
          rows={[
            ['New Request Submitted', 'Admin, HR, Super Admin', 'Agent name, dates, reason, duration, reference number.'],
            ['Request Updated (re-submitted)', 'Admin, HR, Super Admin', 'Updated details with "Updated" flag.'],
            ['Override Request', 'Admin, HR, Super Admin', 'Includes override reason and conflicting agent names.'],
            ['Decision (Approved/Declined)', 'Requesting Agent', 'Status, reviewer name, and any remarks.'],
          ]}
        />

        <CalloutBox variant="tip" title="De-duplicated Recipients">
          If a user holds multiple roles (e.g., Admin + HR), they receive only one notification email per event — never duplicates.
        </CalloutBox>
      </GuideSection>

      {/* 9. Outage Statistics */}
      <GuideSection letter="I" color="bg-amber-500" title="Outage Statistics & HR Policy Integration">
        <p className="text-muted-foreground mb-4">
          The Outage Stats page provides analytics on team outages with HR policy thresholds for identifying patterns.
        </p>

        <h3 className="font-semibold mb-2">HR Policy Threshold Tiers</h3>
        <QuickTable
          headers={['Tier', 'Badge', 'Meaning']}
          rows={[
            ['Acceptable', 'None', 'Within normal range for the outage reason.'],
            ['Needs Review', 'Yellow', 'Approaching threshold — coaching may be needed.'],
            ['Action Required', 'Red', 'Exceeds threshold — formal action recommended.'],
          ]}
        />

        <h3 className="font-semibold mb-2 mt-4">Available Analytics</h3>
        <Checklist items={[
          'Summary dashboard: total outages by reason, status, and period.',
          'Agent breakdown: individual outage counts and patterns.',
          'Trend analysis: month-over-month and week-over-week changes.',
          'Repeat offender tracking with yellow (Needs Review) and red (Action Required) badges.',
          'Team comparison: outage rates across teams.',
          'Planned Leave is excluded from threshold calculations.',
        ]} />

        <GuideImagePlaceholder description="Screenshot: Outage Statistics dashboard with HR policy tier badges" />

        <CalloutBox variant="warning" title="Repeat Offender Patterns">
          Use repeat offender data to identify coaching opportunities. Consistent patterns (e.g., multiple late logins in a rolling period) may indicate scheduling issues that need addressing proactively.
        </CalloutBox>
      </GuideSection>
    </>
  );
}
