import { useState, useEffect, useRef } from 'react';
import { Layout } from '@/components/Layout';
import { useAuth } from '@/context/AuthContext';
import { PageGuideButton } from '@/components/PageGuideButton';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { Loader2, AlertTriangle, Clock, CheckCircle2, XCircle, Ban, Pencil, Upload, X, FileText, History, Trash2, ShieldAlert } from 'lucide-react';
import { LeaveAuditLog } from '@/components/leave/LeaveAuditLog';
import { format, parseISO } from 'date-fns';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import {
  createLeaveRequest,
  updateLeaveRequest,
  adminUpdateLeaveRequest,
  fetchMyLeaveRequests,
  fetchAllLeaveRequests,
  checkConflicts,
  updateLeaveRequestStatus,
  cancelLeaveRequest,
  uploadAttachment,
  fetchLeaveRequestHistory,
  deleteLeaveRequest,
  updateAutoGeneratedRemarks,
  parseAttachmentUrls,
  serializeAttachmentUrls,
  LeaveRequest as LeaveRequestType,
  LeaveRequestInput,
  LeaveRequestHistory
} from '@/lib/leaveRequestApi';
import { supabase } from '@/integrations/supabase/client';
import { getAgentInfoByEmail, getAgentClients, CLIENT_OPTIONS, AGENT_DIRECTORY } from '@/lib/agentDirectory';
import { DatePicker } from '@/components/ui/date-picker';

// Get all agents for dropdown
const ALL_AGENTS = Object.entries(AGENT_DIRECTORY).map(([email, info]) => ({
  email,
  name: info.name,
  position: info.position,
  teamLead: info.teamLead,
  clients: info.clients
})).sort((a, b) => a.name.localeCompare(b.name));

// Get unique team leads
const TEAM_LEADS = [...new Set(Object.values(AGENT_DIRECTORY).map(a => a.teamLead).filter(Boolean))].sort();

// Get unique roles/positions
const ROLES = [...new Set(Object.values(AGENT_DIRECTORY).map(a => a.position))].sort();

const OUTAGE_REASONS = [
  'Power Outage',
  'Wi-Fi Issue',
  'Medical Leave',
  'Planned Leave',
  'Equipment Issue',
  'Late Login',
  'Undertime',
  'Unplanned'
];

const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-warning/10 text-warning border-warning/20',
  pending_override: 'bg-orange-100 text-orange-700 border-orange-200',
  approved: 'bg-success/10 text-success border-success/20',
  declined: 'bg-destructive/10 text-destructive border-destructive/20',
  canceled: 'bg-muted text-muted-foreground border-muted',
  for_review: 'bg-blue-100 text-blue-700 border-blue-200'
};

const STATUS_ICONS: Record<string, React.ReactNode> = {
  pending: <Clock className="h-3 w-3" />,
  pending_override: <ShieldAlert className="h-3 w-3" />,
  approved: <CheckCircle2 className="h-3 w-3" />,
  declined: <XCircle className="h-3 w-3" />,
  canceled: <Ban className="h-3 w-3" />,
  for_review: <Clock className="h-3 w-3" />
};

export default function LeaveRequest() {
  const { user, isAdmin, isHR } = useAuth();
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [requests, setRequests] = useState<LeaveRequestType[]>([]);
  const [conflictWarning, setConflictWarning] = useState<string | null>(null);
  const [conflictingAgents, setConflictingAgents] = useState<string[]>([]);
  const [showOverrideOption, setShowOverrideOption] = useState(false);
  const [overrideReason, setOverrideReason] = useState('');
  const [agentClients, setAgentClients] = useState<string[]>(CLIENT_OPTIONS);
  const [isDirectoryUser, setIsDirectoryUser] = useState(false);
  const [editingRequest, setEditingRequest] = useState<LeaveRequestType | null>(null);
  const [isAdminEditing, setIsAdminEditing] = useState(false);
  const [auditLogOpen, setAuditLogOpen] = useState(false);
  const [selectedRequestForAudit, setSelectedRequestForAudit] = useState<string | null>(null);
  const [auditAgentName, setAuditAgentName] = useState('');
  const [activeTab, setActiveTab] = useState('pending');
  const [selectedRequests, setSelectedRequests] = useState<string[]>([]);
  const [isDeletingBulk, setIsDeletingBulk] = useState(false);
  
  // Decision dialog state
  const [decisionDialog, setDecisionDialog] = useState<{
    open: boolean;
    requestId: string;
    decision: 'approved' | 'declined' | 'canceled';
    agentName: string;
  } | null>(null);
  const [decisionRemarks, setDecisionRemarks] = useState('');
  const [isProcessingDecision, setIsProcessingDecision] = useState(false);
  
  // History dialog state
  const [historyDialog, setHistoryDialog] = useState<{
    open: boolean;
    requestId: string;
    agentName: string;
  } | null>(null);
  const [historyData, setHistoryData] = useState<LeaveRequestHistory[]>([]);
  const [isLoadingHistory, setIsLoadingHistory] = useState(false);
  
  // Auto-generated request remarks state
  const [editRemarks, setEditRemarks] = useState('');
  
  // Form state
  const [formData, setFormData] = useState<LeaveRequestInput>({
    agent_name: '',
    client_name: '',
    team_lead_name: '',
    role: '',
    start_date: '',
    end_date: '',
    start_time: '09:00',
    end_time: '17:00',
    outage_reason: '',
    attachment_url: ''
  });

  const canBulkDelete = isAdmin || isHR;

  useEffect(() => {
    if (user?.email) {
      const agentInfo = getAgentInfoByEmail(user.email);
      if (agentInfo) {
        setIsDirectoryUser(true);
        setAgentClients(agentInfo.clients);
        setFormData(prev => ({
          ...prev,
          agent_name: agentInfo.name,
          team_lead_name: agentInfo.teamLead,
          role: agentInfo.position,
          client_name: agentInfo.clients.length === 1 ? agentInfo.clients[0] : ''
        }));
      } else {
        setIsDirectoryUser(false);
        setAgentClients(CLIENT_OPTIONS);
        if (user.name) {
          setFormData(prev => ({ ...prev, agent_name: user.name }));
        }
      }
    }
    loadRequests();
  }, [user]);

  const loadRequests = async () => {
    if (!user?.email) return;
    
    setIsLoading(true);
    const result = isAdmin 
      ? await fetchAllLeaveRequests()
      : await fetchMyLeaveRequests(user.email);
    
    if (result.data) {
      setRequests(result.data);
    } else if (result.error) {
      toast({
        title: 'Error',
        description: result.error,
        variant: 'destructive'
      });
    }
    setIsLoading(false);
  };

  const handleInputChange = (field: keyof LeaveRequestInput, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    setConflictWarning(null);
    setShowOverrideOption(false);
    setConflictingAgents([]);
  };

  // Handle agent selection for admin - auto-populate other fields
  const handleAgentSelect = (agentName: string) => {
    const agent = ALL_AGENTS.find(a => a.name === agentName);
    if (agent) {
      setFormData(prev => ({
        ...prev,
        agent_name: agent.name,
        team_lead_name: agent.teamLead,
        role: agent.position,
        client_name: agent.clients.length === 1 ? agent.clients[0] : prev.client_name
      }));
      setAgentClients(agent.clients);
    } else {
      setFormData(prev => ({ ...prev, agent_name: agentName }));
    }
    setConflictWarning(null);
    setShowOverrideOption(false);
    setConflictingAgents([]);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !user?.email) return;

    const currentUrls = parseAttachmentUrls(formData.attachment_url);
    if (currentUrls.length >= 3) {
      toast({
        title: 'Limit Reached',
        description: 'Maximum 3 attachments allowed',
        variant: 'destructive'
      });
      return;
    }
    
    setIsUploading(true);
    const result = await uploadAttachment(file, user.email);
    
    if (result.data) {
      const updatedUrls = [...currentUrls, result.data];
      setFormData(prev => ({ ...prev, attachment_url: serializeAttachmentUrls(updatedUrls) || '' }));
      toast({
        title: 'Success',
        description: 'File uploaded successfully'
      });
    } else if (result.error) {
      toast({
        title: 'Upload Error',
        description: result.error,
        variant: 'destructive'
      });
    }
    setIsUploading(false);
    // Reset file input so the same file can be selected again
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const removeAttachment = (index: number) => {
    const currentUrls = parseAttachmentUrls(formData.attachment_url);
    const updatedUrls = currentUrls.filter((_, i) => i !== index);
    setFormData(prev => ({ ...prev, attachment_url: serializeAttachmentUrls(updatedUrls) || '' }));
  };

  const clearAttachment = () => {
    setFormData(prev => ({ ...prev, attachment_url: '' }));
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const validateForm = (): boolean => {
    const required: (keyof LeaveRequestInput)[] = [
      'agent_name', 'client_name', 'team_lead_name', 'role',
      'start_date', 'end_date', 'start_time', 'end_time', 'outage_reason'
    ];
    
    for (const field of required) {
      if (!formData[field]) {
        toast({
          title: 'Validation Error',
          description: `${field.replace(/_/g, ' ')} is required`,
          variant: 'destructive'
        });
        return false;
      }
    }
    
    const startDate = new Date(formData.start_date);
    const endDate = new Date(formData.end_date);
    
    if (endDate < startDate) {
      toast({
        title: 'Validation Error',
        description: 'End date must be on or after start date',
        variant: 'destructive'
      });
      return false;
    }
    
    return true;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm() || !user?.email) return;
    
    setIsSubmitting(true);
    
    // Check for conflicts first (exclude current request when editing)
    const conflictResult = await checkConflicts(formData, editingRequest?.id);
    
    if (conflictResult.error) {
      toast({
        title: 'Error',
        description: conflictResult.error,
        variant: 'destructive'
      });
      setIsSubmitting(false);
      return;
    }
    
    if (conflictResult.data?.hasConflict && !showOverrideOption) {
      const agents = conflictResult.data.conflictingAgents.join(', ');
      setConflictingAgents(conflictResult.data.conflictingAgents);
      setConflictWarning(`Conflict detected with: ${agents}. This time slot overlaps with an existing approved request.`);
      setShowOverrideOption(true);
      setIsSubmitting(false);
      return;
    }
    
    // If override is being requested
    if (showOverrideOption && overrideReason.trim()) {
      // Submit with pending_override status
      const result = await createLeaveRequest({
        ...formData,
        override_reason: overrideReason,
        conflicting_agents: conflictingAgents.join(', '),
        status: 'pending_override'
      } as any, user.email);
      
      if (result.error) {
        toast({
          title: 'Error',
          description: result.error,
          variant: 'destructive'
        });
      } else {
        // Send override notification
        try {
          await supabase.functions.invoke('send-override-request-notification', {
            body: {
              referenceNumber: (result.data as any)?.reference_number || 'LR-0000',
              agentName: formData.agent_name,
              agentEmail: user.email,
              clientName: formData.client_name,
              teamLeadName: formData.team_lead_name,
              role: formData.role,
              startDate: formData.start_date,
              endDate: formData.end_date,
              startTime: formData.start_time,
              endTime: formData.end_time,
              outageReason: formData.outage_reason,
              overrideReason: overrideReason,
              conflictingAgents: conflictingAgents.join(', '),
              totalDays: (result.data as any)?.total_days,
              outageDurationHours: (result.data as any)?.outage_duration_hours
            }
          });
        } catch (notifyErr) {
          console.error('Failed to send override notification:', notifyErr);
        }
        
        toast({
          title: 'Override Request Submitted',
          description: 'Admins have been notified and will review your request.'
        });
        resetForm();
        loadRequests();
      }
      setIsSubmitting(false);
      return;
    }
    
    let result;
    
    if (editingRequest) {
      if (isAdminEditing) {
        result = await adminUpdateLeaveRequest(editingRequest.id, formData, user.email);
      } else {
        const isEditOfNonPending = editingRequest.status !== 'pending';
        result = await updateLeaveRequest(editingRequest.id, formData, user.email, isEditOfNonPending);
        
        if (result.data && isEditOfNonPending) {
          try {
            await supabase.functions.invoke('send-leave-request-notification', {
              body: {
                agentName: formData.agent_name,
                agentEmail: user.email,
                clientName: formData.client_name,
                teamLeadName: formData.team_lead_name,
                role: formData.role,
                startDate: formData.start_date,
                endDate: formData.end_date,
                startTime: formData.start_time,
                endTime: formData.end_time,
                outageReason: formData.outage_reason,
                attachmentUrl: formData.attachment_url,
                totalDays: result.data.total_days,
                outageDurationHours: result.data.outage_duration_hours,
                isUpdated: true
              }
            });
          } catch (notifyErr) {
            console.error('Failed to send notification:', notifyErr);
          }
        }
      }
    } else {
      result = await createLeaveRequest(formData, user.email);
      
      if (result.data) {
        try {
          await supabase.functions.invoke('send-leave-request-notification', {
            body: {
              agentName: formData.agent_name,
              agentEmail: user.email,
              clientName: formData.client_name,
              teamLeadName: formData.team_lead_name,
              role: formData.role,
              startDate: formData.start_date,
              endDate: formData.end_date,
              startTime: formData.start_time,
              endTime: formData.end_time,
              outageReason: formData.outage_reason,
              attachmentUrl: formData.attachment_url,
              totalDays: result.data.total_days,
              outageDurationHours: result.data.outage_duration_hours,
              referenceNumber: result.data.reference_number
            }
          });
        } catch (notifyErr) {
          console.error('Failed to send notification:', notifyErr);
        }
      }
    }
    
    if (result.error) {
      toast({
        title: 'Error',
        description: result.error,
        variant: 'destructive'
      });
    } else {
      // If editing auto-generated request with remarks, save remarks
      if (editingRequest && (editingRequest as any).is_auto_generated && editRemarks && user?.email) {
        await updateAutoGeneratedRemarks(editingRequest.id, editRemarks, user.email);
      }
      
      toast({
        title: 'Success',
        description: editingRequest ? 'Outage request updated successfully' : 'Outage request submitted successfully'
      });
      resetForm();
      loadRequests();
    }
    
    setIsSubmitting(false);
  };

  const resetForm = () => {
    setEditingRequest(null);
    setIsAdminEditing(false);
    setConflictWarning(null);
    setShowOverrideOption(false);
    setConflictingAgents([]);
    setOverrideReason('');
    setEditRemarks('');
    
    const agentInfo = user?.email ? getAgentInfoByEmail(user.email) : null;
    if (agentInfo) {
      setFormData({
        agent_name: agentInfo.name,
        client_name: agentInfo.clients.length === 1 ? agentInfo.clients[0] : '',
        team_lead_name: agentInfo.teamLead,
        role: agentInfo.position,
        start_date: '',
        end_date: '',
        start_time: '09:00',
        end_time: '17:00',
        outage_reason: '',
        attachment_url: ''
      });
    } else {
      setFormData({
        agent_name: user?.name || '',
        client_name: '',
        team_lead_name: '',
        role: '',
        start_date: '',
        end_date: '',
        start_time: '09:00',
        end_time: '17:00',
        outage_reason: '',
        attachment_url: ''
      });
    }
  };
  
  const handleEdit = (req: LeaveRequestType, adminEdit: boolean = false) => {
    setEditingRequest(req);
    setIsAdminEditing(adminEdit);
    setFormData({
      agent_name: req.agent_name,
      client_name: req.client_name,
      team_lead_name: req.team_lead_name,
      role: req.role,
      start_date: req.start_date,
      end_date: req.end_date,
      start_time: req.start_time,
      end_time: req.end_time,
      outage_reason: req.outage_reason,
      attachment_url: req.attachment_url || ''
    });
    // Load remarks for auto-generated requests
    setEditRemarks(req.remarks || '');
    setConflictWarning(null);
    setShowOverrideOption(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
  
  const handleCancelEdit = () => {
    resetForm();
  };

  const openDecisionDialog = (requestId: string, decision: 'approved' | 'declined' | 'canceled', agentName: string) => {
    setDecisionDialog({ open: true, requestId, decision, agentName });
    setDecisionRemarks('');
  };

  const handleConfirmDecision = async () => {
    if (!decisionDialog || !user?.email) return;
    
    setIsProcessingDecision(true);
    const result = await updateLeaveRequestStatus(
      decisionDialog.requestId, 
      decisionDialog.decision, 
      user.email,
      decisionRemarks || undefined
    );
    
    if (result.error) {
      toast({
        title: 'Error',
        description: result.error,
        variant: 'destructive'
      });
    } else {
      toast({
        title: 'Success',
        description: `Request ${decisionDialog.decision}`
      });
      loadRequests();
    }
    
    setIsProcessingDecision(false);
    setDecisionDialog(null);
    setDecisionRemarks('');
  };

  const handleApproveOverride = async (requestId: string) => {
    if (!user?.email) return;
    
    setIsProcessingDecision(true);
    const result = await updateLeaveRequestStatus(requestId, 'approved', user.email, 'Override approved by admin');
    
    if (result.error) {
      toast({
        title: 'Error',
        description: result.error,
        variant: 'destructive'
      });
    } else {
      toast({
        title: 'Success',
        description: 'Override request approved'
      });
      loadRequests();
    }
    setIsProcessingDecision(false);
  };

  const openHistoryDialog = (requestId: string, agentName: string) => {
    setSelectedRequestForAudit(requestId);
    setAuditAgentName(agentName);
    setAuditLogOpen(true);
  };

  const formatFieldName = (field: string): string => {
    return field.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  };

  const formatFieldValue = (value: unknown): string => {
    if (value === null || value === undefined) return '-';
    if (typeof value === 'string') return value;
    return String(value);
  };

  const handleCancel = async (id: string) => {
    if (!user?.email) return;
    
    const result = await cancelLeaveRequest(id, user.email);
    
    if (result.error) {
      toast({
        title: 'Error',
        description: result.error,
        variant: 'destructive'
      });
    } else {
      toast({
        title: 'Success',
        description: 'Request canceled'
      });
      loadRequests();
    }
  };

  const handleDelete = async (id: string) => {
    const result = await deleteLeaveRequest(id);
    
    if (result.error) {
      toast({
        title: 'Error',
        description: result.error,
        variant: 'destructive'
      });
    } else {
      toast({
        title: 'Success',
        description: 'Request deleted'
      });
      loadRequests();
    }
  };

  const handleBulkDelete = async () => {
    if (selectedRequests.length === 0) return;
    
    setIsDeletingBulk(true);
    let successCount = 0;
    let errorCount = 0;
    
    for (const id of selectedRequests) {
      const result = await deleteLeaveRequest(id);
      if (result.error) {
        errorCount++;
      } else {
        successCount++;
      }
    }
    
    setIsDeletingBulk(false);
    setSelectedRequests([]);
    
    if (errorCount > 0) {
      toast({
        title: 'Partial Success',
        description: `Deleted ${successCount} requests. ${errorCount} failed.`,
        variant: 'destructive'
      });
    } else {
      toast({
        title: 'Success',
        description: `Deleted ${successCount} requests`
      });
    }
    
    loadRequests();
  };

  const toggleSelectRequest = (id: string) => {
    setSelectedRequests(prev => 
      prev.includes(id) ? prev.filter(r => r !== id) : [...prev, id]
    );
  };

  const toggleSelectAll = (requests: LeaveRequestType[]) => {
    if (selectedRequests.length === requests.length) {
      setSelectedRequests([]);
    } else {
      setSelectedRequests(requests.map(r => r.id));
    }
  };


  const overrideCount = requests.filter(r => (r.status as string) === 'pending_override').length;

  // Filter requests based on active tab
  const filteredRequests = 
    activeTab === 'override' ? requests.filter(r => (r.status as string) === 'pending_override')
    : activeTab === 'pending' ? requests.filter(r => (r.status as string) === 'pending')
    : activeTab === 'for_review' ? requests.filter(r => (r.status as string) === 'for_review')
    : requests;

  return (
    <Layout>
      <div className="space-y-6 animate-fade-in">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold text-foreground">Outage Requests</h1>
            <p className="text-muted-foreground">Submit and manage your outage requests</p>
          </div>
          <PageGuideButton pageId="leave-request" />
        </div>

        {/* Submit Form */}
        <Card>
          <CardHeader>
            <CardTitle>
              {editingRequest 
                ? (isAdminEditing ? 'Edit Request (Admin)' : 'Edit Request') 
                : 'Submit New Request'
              }
            </CardTitle>
            <CardDescription>
              {editingRequest && !isAdminEditing && editingRequest.status !== 'pending'
                ? 'Editing will reset this request to pending status'
                : 'Fill in all required fields to submit a leave request'
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              {conflictWarning && (
                <div className="flex items-start gap-2 p-3 bg-destructive/10 border border-destructive/20 rounded-lg text-destructive">
                  <AlertTriangle className="h-5 w-5 flex-shrink-0 mt-0.5" />
                  <div className="flex-1">
                    <span className="text-sm font-medium">{conflictWarning}</span>
                    {showOverrideOption && (
                      <div className="mt-3 space-y-2">
                        <p className="text-sm text-muted-foreground">
                          You can request an override approval from admins. Please provide a reason:
                        </p>
                        <Textarea
                          placeholder="Explain why this request should be approved despite the conflict..."
                          value={overrideReason}
                          onChange={(e) => setOverrideReason(e.target.value)}
                          rows={2}
                          className="bg-background"
                        />
                      </div>
                    )}
                  </div>
                </div>
              )}
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Notice for users editing */}
                {editingRequest && !isAdmin && (
                  <div className="md:col-span-2 p-3 bg-muted/50 border rounded-lg">
                    <p className="text-sm text-muted-foreground">
                      <strong>Note:</strong> Core details are read-only. You can only update remarks.
                    </p>
                  </div>
                )}

                <div className="space-y-2">
                  <Label htmlFor="agent_name">Agent Name *</Label>
                  {isAdmin ? (
                    <Select
                      value={formData.agent_name}
                      onValueChange={handleAgentSelect}
                      disabled={!!editingRequest && !isAdmin}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select agent" />
                      </SelectTrigger>
                      <SelectContent>
                        {ALL_AGENTS.map(agent => (
                          <SelectItem key={agent.email} value={agent.name}>{agent.name}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  ) : (
                    <Input
                      id="agent_name"
                      value={formData.agent_name}
                      onChange={(e) => handleInputChange('agent_name', e.target.value)}
                      placeholder="Your name"
                      disabled={isDirectoryUser || (!!editingRequest && !isAdmin)}
                      className={(isDirectoryUser || (!!editingRequest && !isAdmin)) ? 'bg-muted' : ''}
                    />
                  )}
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="client_name">Client Name *</Label>
                  <Select
                    value={formData.client_name}
                    onValueChange={(value) => handleInputChange('client_name', value)}
                    disabled={!!editingRequest && !isAdmin}
                  >
                    <SelectTrigger className={(!!editingRequest && !isAdmin) ? 'bg-muted' : ''}>
                      <SelectValue placeholder="Select client" />
                    </SelectTrigger>
                    <SelectContent>
                      {(isAdmin ? CLIENT_OPTIONS : agentClients).map(client => (
                        <SelectItem key={client} value={client}>{client}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="team_lead_name">Team Lead Name *</Label>
                  {isAdmin ? (
                    <Select
                      value={formData.team_lead_name}
                      onValueChange={(value) => handleInputChange('team_lead_name', value)}
                      disabled={!!editingRequest && !isAdmin}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select team lead" />
                      </SelectTrigger>
                      <SelectContent>
                        {TEAM_LEADS.map(lead => (
                          <SelectItem key={lead} value={lead}>{lead}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  ) : (
                    <Input
                      id="team_lead_name"
                      value={formData.team_lead_name}
                      onChange={(e) => handleInputChange('team_lead_name', e.target.value)}
                      placeholder="Team lead name"
                      disabled={isDirectoryUser || (!!editingRequest && !isAdmin)}
                      className={(isDirectoryUser || (!!editingRequest && !isAdmin)) ? 'bg-muted' : ''}
                    />
                  )}
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="role">Role *</Label>
                  {isAdmin ? (
                    <Select
                      value={formData.role}
                      onValueChange={(value) => handleInputChange('role', value)}
                      disabled={!!editingRequest && !isAdmin}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select role" />
                      </SelectTrigger>
                      <SelectContent>
                        {ROLES.map(role => (
                          <SelectItem key={role} value={role}>{role}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  ) : (
                    <Input
                      id="role"
                      value={formData.role}
                      onChange={(e) => handleInputChange('role', e.target.value)}
                      placeholder="Your role"
                      disabled={isDirectoryUser || (!!editingRequest && !isAdmin)}
                      className={(isDirectoryUser || (!!editingRequest && !isAdmin)) ? 'bg-muted' : ''}
                    />
                  )}
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="start_date">Start Date *</Label>
                  <DatePicker
                    id="start_date"
                    value={formData.start_date}
                    onChange={(value) => handleInputChange('start_date', value)}
                    placeholder="Select start date"
                    disabled={!!editingRequest && !isAdmin}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="end_date">End Date *</Label>
                  <DatePicker
                    id="end_date"
                    value={formData.end_date}
                    onChange={(value) => handleInputChange('end_date', value)}
                    placeholder="Select end date"
                    disabled={!!editingRequest && !isAdmin}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="start_time">Start Time (EST) *</Label>
                  <Input
                    id="start_time"
                    type="time"
                    value={formData.start_time}
                    onChange={(e) => handleInputChange('start_time', e.target.value)}
                    disabled={!!editingRequest && !isAdmin}
                    className={(!!editingRequest && !isAdmin) ? 'bg-muted' : ''}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="end_time">End Time (EST) *</Label>
                  <Input
                    id="end_time"
                    type="time"
                    value={formData.end_time}
                    onChange={(e) => handleInputChange('end_time', e.target.value)}
                    disabled={!!editingRequest && !isAdmin}
                    className={(!!editingRequest && !isAdmin) ? 'bg-muted' : ''}
                  />
                </div>
                
                <div className="space-y-2 md:col-span-2">
                  <Label htmlFor="outage_reason">Outage Reason *</Label>
                  <Select
                    value={formData.outage_reason}
                    onValueChange={(value) => handleInputChange('outage_reason', value)}
                    disabled={!!editingRequest && !isAdmin}
                  >
                    <SelectTrigger className={(!!editingRequest && !isAdmin) ? 'bg-muted' : ''}>
                      <SelectValue placeholder="Select reason" />
                    </SelectTrigger>
                    <SelectContent>
                      {OUTAGE_REASONS.map(reason => (
                        <SelectItem key={reason} value={reason}>{reason}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2 md:col-span-2">
                  <Label>Attachments (optional, max 3)</Label>
                  <div className="space-y-2">
                    <Input
                      ref={fileInputRef}
                      type="file"
                      onChange={handleFileUpload}
                      disabled={isUploading || (!!editingRequest && !isAdmin)}
                      className="hidden"
                      id="file-upload"
                    />
                    {/* List of uploaded attachments */}
                    {parseAttachmentUrls(formData.attachment_url).map((url, idx) => (
                      <div key={idx} className="flex items-center gap-2 p-2 border rounded-lg">
                        <FileText className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                        <a 
                          href={url} 
                          target="_blank" 
                          rel="noopener noreferrer"
                          className="text-sm text-primary hover:underline truncate flex-1"
                        >
                          Attachment {idx + 1}
                        </a>
                        {(isAdmin || !editingRequest) && (
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            onClick={() => removeAttachment(idx)}
                            className="h-6 w-6"
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        )}
                      </div>
                    ))}
                    {/* Upload button - show if under limit */}
                    {parseAttachmentUrls(formData.attachment_url).length < 3 && (
                      <Button
                        type="button"
                        variant="outline"
                        onClick={() => fileInputRef.current?.click()}
                        disabled={isUploading || (!!editingRequest && !isAdmin)}
                        className="w-full justify-start"
                      >
                        {isUploading ? (
                          <>
                            <Loader2 className="h-4 w-4 animate-spin mr-2" />
                            Uploading...
                          </>
                        ) : (
                          <>
                            <Upload className="h-4 w-4 mr-2" />
                            {parseAttachmentUrls(formData.attachment_url).length > 0 ? 'Add Another File' : 'Choose File'}
                          </>
                        )}
                      </Button>
                    )}
                    <p className="text-xs text-muted-foreground">
                      {parseAttachmentUrls(formData.attachment_url).length}/3 files attached
                    </p>
                  </div>
                </div>
                
                {/* Remarks field - always visible when editing */}
                {editingRequest && (
                  <div className="space-y-2 md:col-span-2">
                    <Label htmlFor="edit_remarks">Remarks</Label>
                    <Textarea
                      id="edit_remarks"
                      value={editRemarks}
                      onChange={(e) => setEditRemarks(e.target.value)}
                      placeholder="Add any notes or explanation..."
                      rows={3}
                    />
                    <p className="text-xs text-muted-foreground">
                      {(editingRequest as any).is_auto_generated 
                        ? 'This request was auto-generated. Use remarks to provide additional context.'
                        : 'Use remarks to add context or explanation for this request.'}
                    </p>
                  </div>
                )}
              </div>
              
              <div className="flex gap-2">
                <Button 
                  type="submit" 
                  disabled={isSubmitting || isUploading} 
                  className="w-full md:w-auto"
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin mr-2" />
                      {editingRequest ? 'Updating...' : showOverrideOption ? 'Submitting Override...' : 'Submitting...'}
                    </>
                  ) : (
                    showOverrideOption ? 'Submit for Override Approval' : (editingRequest ? 'Update Request' : 'Submit Request')
                  )}
                </Button>
                {editingRequest && (
                  <Button type="button" variant="outline" onClick={handleCancelEdit}>
                    Cancel Edit
                  </Button>
                )}
              </div>
            </form>
          </CardContent>
        </Card>

        {/* Requests Table */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>{isAdmin ? 'All Outage Requests' : 'My Outage Requests'}</CardTitle>
                <CardDescription>
                  {isAdmin ? 'Review and approve/decline outage requests' : 'View the status of your outage requests'}
                </CardDescription>
              </div>
              {canBulkDelete && selectedRequests.length > 0 && (
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button variant="destructive" size="sm" disabled={isDeletingBulk}>
                      {isDeletingBulk ? (
                        <Loader2 className="h-4 w-4 animate-spin mr-2" />
                      ) : (
                        <Trash2 className="h-4 w-4 mr-2" />
                      )}
                      Delete Selected ({selectedRequests.length})
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Delete Selected Requests</AlertDialogTitle>
                      <AlertDialogDescription>
                        Are you sure you want to delete {selectedRequests.length} leave request(s)? This action cannot be undone.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={handleBulkDelete}
                        className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                      >
                        Delete All
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {isAdmin && (
              <Tabs value={activeTab} onValueChange={setActiveTab} className="mb-4">
                <TabsList data-tour="request-tabs">
                  <TabsTrigger value="pending">Pending</TabsTrigger>
                  <TabsTrigger value="for_review">For Review</TabsTrigger>
                  <TabsTrigger value="override" className="relative">
                    Override Requests
                    {overrideCount > 0 && (
                      <Badge variant="destructive" className="ml-2 h-5 w-5 p-0 flex items-center justify-center text-xs">
                        {overrideCount}
                      </Badge>
                    )}
                  </TabsTrigger>
                  <TabsTrigger value="all">All Requests</TabsTrigger>
                </TabsList>
              </Tabs>
            )}
            
            {!isAdmin && (
              <Tabs value={activeTab} onValueChange={setActiveTab} className="mb-4">
                <TabsList data-tour="request-tabs">
                  <TabsTrigger value="pending">Pending</TabsTrigger>
                  <TabsTrigger value="all">All Requests</TabsTrigger>
                </TabsList>
              </Tabs>
            )}
            
            {isLoading ? (
              <div className="flex justify-center py-8">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : filteredRequests.length === 0 ? (
              <p className="text-center text-muted-foreground py-8">
                {activeTab === 'override' ? 'No override requests pending' : 'No outage requests found'}
              </p>
            ) : (
              <div className="overflow-x-auto">
                <Table data-tour="requests-list">
                  <TableHeader>
                    <TableRow>
                      {canBulkDelete && (
                        <TableHead className="w-10">
                          <Checkbox
                            checked={selectedRequests.length === filteredRequests.length && filteredRequests.length > 0}
                            onCheckedChange={() => toggleSelectAll(filteredRequests)}
                          />
                        </TableHead>
                      )}
                      <TableHead>Ref #</TableHead>
                      <TableHead>Submitted</TableHead>
                      <TableHead>Agent</TableHead>
                      <TableHead>Client</TableHead>
                      <TableHead>Dates</TableHead>
                      <TableHead>Times</TableHead>
                      <TableHead>Reason</TableHead>
                      <TableHead>Status</TableHead>
                      {isAdmin && <TableHead>Remarks</TableHead>}
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredRequests.map((req) => (
                      <TableRow key={req.id}>
                        {canBulkDelete && (
                          <TableCell>
                            <Checkbox
                              checked={selectedRequests.includes(req.id)}
                              onCheckedChange={() => toggleSelectRequest(req.id)}
                            />
                          </TableCell>
                        )}
                        <TableCell>
                          <div className="flex items-center gap-1">
                            <Badge variant="outline" className="font-mono text-xs">
                              {(req as any).reference_number || '-'}
                            </Badge>
                            {(req as any).is_auto_generated && (
                              <Badge variant="secondary" className="text-xs bg-blue-100 text-blue-700">
                                Auto
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <span className="text-sm text-muted-foreground">
                            {format(parseISO(req.created_at), 'MMM d, yyyy')}
                          </span>
                        </TableCell>
                        <TableCell>
                          <div>
                            <p className="font-medium">{req.agent_name}</p>
                            <p className="text-xs text-muted-foreground">{req.role}</p>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div>
                            <p>{req.client_name}</p>
                            <p className="text-xs text-muted-foreground">{req.team_lead_name}</p>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm">
                            <p>{format(parseISO(req.start_date), 'MMM d, yyyy')}</p>
                            <p className="text-muted-foreground">to {format(parseISO(req.end_date), 'MMM d, yyyy')}</p>
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm">
                            <p>{req.start_time} - {req.end_time}</p>
                            {req.total_days && req.daily_hours && (
                              <p className="text-xs text-muted-foreground">
                                {req.total_days}d × {req.daily_hours}h = {req.outage_duration_hours}h
                              </p>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="space-y-1">
                            <span>{req.outage_reason}</span>
                            {parseAttachmentUrls(req.attachment_url).map((url, idx) => (
                              <a 
                                key={idx}
                                href={url} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-1 text-xs text-primary hover:underline"
                              >
                                <FileText className="h-3 w-3" />
                                Attachment {idx + 1}
                              </a>
                            ))}
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline" className={STATUS_COLORS[req.status] || ''}>
                            <span className="flex items-center gap-1">
                              {STATUS_ICONS[req.status]}
                              {req.status === 'pending_override' ? 'Override Pending' : 
                               req.status === 'for_review' ? 'For Review' :
                               req.status.charAt(0).toUpperCase() + req.status.slice(1)}
                            </span>
                          </Badge>
                          {req.status === 'pending_override' && (req as any).override_reason && (
                            <p className="text-xs text-muted-foreground mt-1 max-w-[150px] truncate" title={(req as any).override_reason}>
                              Reason: {(req as any).override_reason}
                            </p>
                          )}
                        </TableCell>
                        {isAdmin && (
                          <TableCell>
                            <p className="text-xs text-muted-foreground max-w-[150px] truncate" title={req.remarks || ''}>
                              {req.remarks || '-'}
                            </p>
                          </TableCell>
                        )}
                        <TableCell>
                          <div className="flex gap-2 flex-wrap">
                            {isAdmin && req.status === 'pending_override' && (
                              <>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="text-success hover:text-success"
                                  onClick={() => handleApproveOverride(req.id)}
                                  disabled={isProcessingDecision}
                                >
                                  {isProcessingDecision ? <Loader2 className="h-3 w-3 animate-spin" /> : 'Approve Override'}
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="text-destructive hover:text-destructive"
                                  onClick={() => openDecisionDialog(req.id, 'declined', req.agent_name)}
                                >
                                  Decline
                                </Button>
                              </>
                            )}
                            {isAdmin && (req.status === 'pending' || req.status === 'for_review') && (
                              <Button
                                size="sm"
                                variant="outline"
                                className="text-success hover:text-success"
                                onClick={() => openDecisionDialog(req.id, 'approved', req.agent_name)}
                              >
                                Approve
                              </Button>
                            )}
                            {isAdmin && (req.status === 'pending' || req.status === 'approved' || req.status === 'for_review') && (
                              <>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="text-destructive hover:text-destructive"
                                  onClick={() => openDecisionDialog(req.id, 'declined', req.agent_name)}
                                >
                                  Decline
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="text-muted-foreground hover:text-muted-foreground"
                                  onClick={() => openDecisionDialog(req.id, 'canceled', req.agent_name)}
                                >
                                  Cancel
                                </Button>
                              </>
                            )}
                            {isAdmin && (
                              <>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  onClick={() => handleEdit(req, true)}
                                >
                                  <Pencil className="h-3 w-3 mr-1" />
                                  Edit
                                </Button>
                                <Button
                                  size="sm"
                                  variant="ghost"
                                  onClick={() => openHistoryDialog(req.id, req.agent_name)}
                                  title="View History"
                                >
                                  <History className="h-3 w-3" />
                                </Button>
                                <AlertDialog>
                                  <AlertDialogTrigger asChild>
                                    <Button
                                      size="sm"
                                      variant="ghost"
                                      className="text-destructive hover:text-destructive"
                                      title="Delete"
                                    >
                                      <Trash2 className="h-3 w-3" />
                                    </Button>
                                  </AlertDialogTrigger>
                                  <AlertDialogContent>
                                    <AlertDialogHeader>
                                      <AlertDialogTitle>Delete Outage Request</AlertDialogTitle>
                                      <AlertDialogDescription>
                                        Are you sure you want to delete this outage request from {req.agent_name}? This action cannot be undone.
                                      </AlertDialogDescription>
                                    </AlertDialogHeader>
                                    <AlertDialogFooter>
                                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                                      <AlertDialogAction
                                        onClick={() => handleDelete(req.id)}
                                        className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                                      >
                                        Delete
                                      </AlertDialogAction>
                                    </AlertDialogFooter>
                                  </AlertDialogContent>
                                </AlertDialog>
                              </>
                            )}
                            {!isAdmin && req.agent_email === user?.email?.toLowerCase() && (
                              <>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  onClick={() => handleEdit(req, false)}
                                >
                                  <Pencil className="h-3 w-3 mr-1" />
                                  Edit
                                </Button>
                                {(req.status === 'pending' || req.status === 'approved') && (
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    className="text-destructive hover:text-destructive"
                                    onClick={() => handleCancel(req.id)}
                                  >
                                    Cancel
                                  </Button>
                                )}
                              </>
                            )}
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Decision Dialog */}
      <Dialog open={decisionDialog?.open || false} onOpenChange={(open) => !open && setDecisionDialog(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {decisionDialog?.decision === 'approved' && 'Approve Request'}
              {decisionDialog?.decision === 'declined' && 'Decline Request'}
              {decisionDialog?.decision === 'canceled' && 'Cancel Request'}
            </DialogTitle>
            <DialogDescription>
              {decisionDialog?.decision === 'approved' && `Approve the leave request for ${decisionDialog?.agentName}?`}
              {decisionDialog?.decision === 'declined' && `Decline the leave request for ${decisionDialog?.agentName}?`}
              {decisionDialog?.decision === 'canceled' && `Cancel the leave request for ${decisionDialog?.agentName}?`}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="remarks">Remarks (optional)</Label>
              <Textarea
                id="remarks"
                value={decisionRemarks}
                onChange={(e) => setDecisionRemarks(e.target.value)}
                placeholder="Add any notes or reason for this decision..."
                rows={3}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDecisionDialog(null)} disabled={isProcessingDecision}>
              Cancel
            </Button>
            <Button 
              onClick={handleConfirmDecision} 
              disabled={isProcessingDecision}
              className={
                decisionDialog?.decision === 'approved' ? 'bg-success hover:bg-success/90' :
                decisionDialog?.decision === 'declined' ? 'bg-destructive hover:bg-destructive/90' : ''
              }
            >
              {isProcessingDecision ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                  Processing...
                </>
              ) : (
                `Confirm ${decisionDialog?.decision?.charAt(0).toUpperCase()}${decisionDialog?.decision?.slice(1)}`
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Audit Log Dialog */}
      <LeaveAuditLog
        isOpen={auditLogOpen}
        onOpenChange={setAuditLogOpen}
        requestId={selectedRequestForAudit}
        agentName={auditAgentName}
      />
    </Layout>
  );
}
